title: Siddharth Mundra
logo: assets/Photo_SidMundra.jpg
description: >
  Junior at UC San Diego majoring in Computer Science and minoring in Finance
  <br>
  <br>
  <b>Email: smundra@ucsd.edu</b>
  <br>
  <br>
  <a href="/projects/projects.html"><b>Projects</b></a>
  <br>
  <br>
  <a href="/experience/experience.html"><b>Experience</b></a>
  <br>
  <br>
  <a href="https://drive.google.com/file/d/1Iu4LRMAtY2yptWy5bja_c5JNFPx-SJVr/view?usp=sharing"><b>Resume</b></a>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/siddharthmundra04"><b>LinkedIn (inactive)</b></a>
  <br>
  <br>
  <a href="https://stackoverflow.com/users/16408088/siddharth-mundra"><b>Stack Overflow</b></a>
  <br>
remote_theme: pages-themes/minimal@v0.2.0
